packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
